import type { Metadata } from 'next'
import { inter } from '@/fonts/fonts'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Menu from '@/components/Menu'

export const metadata: Metadata = {
  title: 'Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased min-w-[300px] w-full`}>
        <section className='border-none fixed top-0 overflow-hidden w-full h-auto z-20'>
          <Header />
          <Menu />
        </section>
        <main className='mt-[127px] sm:mt-[110px] min-h-screen w-full mx-auto'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
