import type { Metadata } from 'next'
import { Coming_Soon, Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Menu from '@/components/Menu'

const inter = Inter({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <Header />
        <Menu />
        <main className='min-h-screen w-11/12 mx-auto my-8'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
